apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
data:
  config.yaml: |
    issuer: http://dex.auth.svc.cluster.local:5556/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    logger:
      level: "debug"
      format: text
    oauth2:
      skipApprovalScreen: true
    enablePasswordDB: true
    staticPasswords:
    - email: guest@chunjae.co.kr
      hash: $2y$12$MGmm7M4Y42MzPF6B1S8yUeH49y5Xl2N.sCC2zzYpPCizGLppXVtl2
      username: guest
      userID: "15841185641784"
    - email: ai-devops@chunjae.co.kr
      hash: $2y$12$CK4AwpLGE532q8S7as3QserNDHBzPluqNL2AqeQhCL6faEGaO2U6u. # devops123@
      username: ai-devops
      userID: "15841185641785"
      
    staticClients:
    # https://github.com/dexidp/dex/pull/1664
    - idEnv: OIDC_CLIENT_ID
      redirectURIs: ["/authservice/oidc/callback"]
      name: 'Dex Login Application'
      secretEnv: OIDC_CLIENT_SECRET
