apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
  - name: grafanaui
    nodePort: 30525
    port: 3000
    targetPort: 3000
