apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-storage-claim
spec:
  storageClassName: "" 
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 100Gi
  selector:
    matchExpressions:
      - key: type
        operator: In
        values:
          - nfs