---
apiVersion: v1
kind: Service
metadata:
  name: dex-mysql
  # namespace: auth
  labels:
    dex/component: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
      name: dbapi
  selector:
    dex/component: mysql
