apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "monitoring-dashboard"
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: monitoring-dashboard-alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-path: '/'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '120'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '60'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:{AWS_ACCOUNT_ID}:certificate/{CERTIFICATE_ARN_ID}
    external-dns.alpha.kubernetes.io/hostname: "grafana.kubeflow.{DOMAIN_NAME},prometheus.kubeflow.{DOMAIN_NAME},k8s-dashboard.kubeflow.{DOMAIN_NAME}"
spec:
  rules:
    - host: grafana.kubeflow.{DOMAIN_NAME}
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: prometheus-grafana
              port:
                number: 80

    - host: prometheus.kubeflow.{DOMAIN_NAME}
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: prometheus-kube-prometheus-prometheus
              port:
                number: 9090
    
    - host: k8s-dashboard.kubeflow.{DOMAIN_NAME}
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: kubernetes-dashboard
              port:
                number: 9090
