apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  type: NodePort
  ports:
    - nodePort: 31691
      port: 80
  selector:
    app: istio-ingressgateway